GET http://localhost:3001/api/persons


###

POST http://localhost:3001/api/persons
Content-Type: application/json

{
  "name": "RequestLogger",
  "number": "1234567890"
}


###

GET http://localhost:3001/api/persons/671d4a3b43f35af24b254335


###

DELETE http://localhost:3001/api/persons/671d4a3b43f35af24b254335